apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fluxcd.io/sync-checksum: 6deb427fe35bc6b512b9df8796bd2c16ef25d1a2
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"fluxcd.io/sync-checksum":"6deb427fe35bc6b512b9df8796bd2c16ef25d1a2"},"labels":{"component":"minio","fluxcd.io/sync-gc-mark":"sha256.Sfa36xW17LSAv3TuTQ8qSygIOm_32hF9e-aNR7UPZ7c"},"name":"minio","namespace":"flux"},"spec":{"ports":[{"port":9000,"protocol":"TCP","targetPort":9000}],"selector":{"component":"minio"},"type":"ClusterIP"}}
    creationTimestamp: "2020-05-22T08:55:52Z"
    labels:
      component: minio
      fluxcd.io/sync-gc-mark: sha256.Sfa36xW17LSAv3TuTQ8qSygIOm_32hF9e-aNR7UPZ7c
    name: minio
    namespace: flux
    resourceVersion: "10840122340"
    selfLink: /api/v1/namespaces/flux/services/minio
    uid: b787211f-3e79-43db-9173-a653c0ee048e
  spec:
    clusterIP: 10.3.125.77
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      component: minio
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      fluxcd.io/sync-checksum: 1e5f73c605a85f2fce9455cb2b79148b93e56eb0
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"fluxcd.io/sync-checksum":"1e5f73c605a85f2fce9455cb2b79148b93e56eb0"},"labels":{"component":"minio","fluxcd.io/sync-gc-mark":"sha256.AerVlSZo5htln_Rpt6-H0-Ik2uDcKLJoF7AnBjBQvOM"},"name":"minio","namespace":"flux"},"spec":{"selector":{"matchLabels":{"component":"minio"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"component":"minio"}},"spec":{"containers":[{"args":["server","/storage","--config-dir=/config"],"env":[{"name":"MINIO_ACCESS_KEY","value":"minio"},{"name":"MINIO_SECRET_KEY","value":"minio123"}],"image":"minio/minio:latest","imagePullPolicy":"IfNotPresent","name":"minio","ports":[{"containerPort":9000}],"volumeMounts":[{"mountPath":"/storage","name":"storage"},{"mountPath":"/config","name":"config"}]}],"volumes":[{"emptyDir":{},"name":"storage"},{"emptyDir":{},"name":"config"}]}}}}
    creationTimestamp: "2020-05-22T08:55:52Z"
    generation: 1
    labels:
      component: minio
      fluxcd.io/sync-gc-mark: sha256.AerVlSZo5htln_Rpt6-H0-Ik2uDcKLJoF7AnBjBQvOM
    name: minio
    namespace: flux
    resourceVersion: "10840123992"
    selfLink: /apis/apps/v1/namespaces/flux/deployments/minio
    uid: eeb4bd6e-ac42-43da-abf4-9f323ef41f47
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        component: minio
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: minio
      spec:
        containers:
        - args:
          - server
          - /storage
          - --config-dir=/config
          env:
          - name: MINIO_ACCESS_KEY
            value: minio
          - name: MINIO_SECRET_KEY
            value: minio123
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          name: minio
          ports:
          - containerPort: 9000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /storage
            name: storage
          - mountPath: /config
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: storage
        - emptyDir: {}
          name: config
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-05-22T08:55:56Z"
      lastUpdateTime: "2020-05-22T08:55:56Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-05-22T08:55:52Z"
      lastUpdateTime: "2020-05-22T08:55:56Z"
      message: ReplicaSet "minio-d787f4bf7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"rabbitmq"},"name":"rabbitmq","namespace":"flux"},"spec":{"ports":[{"name":"amqp","port":5672,"targetPort":"amqp"},{"name":"rmq-prometheus","port":15692,"targetPort":"rmq-prometheus"},{"name":"management","port":15672,"targetPort":"management"}],"selector":{"app":"rabbitmq"},"type":"ClusterIP"}}
    labels:
      app: rabbitmq
    name: rabbitmq
    namespace: flux
  spec:
    ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: rmq-prometheus
      port: 15692
      targetPort: rmq-prometheus
    - name: management
      port: 15672
      targetPort: management
    selector:
      app: rabbitmq
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"rabbitmq"},"name":"rabbitmq","namespace":"flux"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rabbitmq"}},"template":{"metadata":{"labels":{"app":"rabbitmq"}},"spec":{"containers":[{"image":"rabbitmq:3.8-management","name":"rabbitmq","ports":[{"containerPort":5672,"name":"amqp"},{"containerPort":15672,"name":"management"},{"containerPort":15672,"name":"rmq-prometheus"}],"resources":{"limits":{"cpu":"300m","memory":"1024Mi"},"requests":{"cpu":"250m","memory":"512Mi"}}}]}}}}
    labels:
      app: rabbitmq
    name: rabbitmq
    namespace: flux
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: rabbitmq
    template:
      metadata:
        labels:
          app: rabbitmq
      spec:
        containers:
        - image: rabbitmq:3.8-management
          name: rabbitmq
          ports:
          - containerPort: 5672
            name: amqp
          - containerPort: 15672
            name: management
          - containerPort: 15672
            name: rmq-prometheus
          resources:
            limits:
              cpu: 300m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 512Mi
kind: List
metadata: {}
